### ISSUE TITLE
Error al instalar dependencias

### ISSUE THREAD

**Issue by davElsanto** [Alejoss/academia_blockchain#1]
Al implementar las dependencias genera el siguiente error al instalar la siguiente dependencia `psycopg2==2.8.5`

`
Collecting psycopg2==2.8.5
  Downloading psycopg2-2.8.5.tar.gz (380 kB)
     |████████████████████████████████| 380 kB 4.8 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/davidsantos/Dev/Env/academiabc/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-i6loh0ad/psycopg2/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-i6loh0ad/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/tmp/pip-pip-egg-info-dlty_xc5
         cwd: /private/tmp/pip-install-i6loh0ad/psycopg2/
    Complete output (23 lines):
    running egg_info
    creating /private/tmp/pip-pip-egg-info-dlty_xc5/psycopg2.egg-info
    writing /private/tmp/pip-pip-egg-info-dlty_xc5/psycopg2.egg-info/PKG-INFO
    writing dependency_links to /private/tmp/pip-pip-egg-info-dlty_xc5/psycopg2.egg-info/dependency_links.txt
    writing top-level names to /private/tmp/pip-pip-egg-info-dlty_xc5/psycopg2.egg-info/top_level.txt
    writing manifest file '/private/tmp/pip-pip-egg-info-dlty_xc5/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

El error se genero usando el siguiente ambiente:

```
Package    Version
---------- ---------
appdirs    1.4.4
certifi    2020.6.20
distlib    0.3.1
filelock   3.0.12
pip        20.2.3
setuptools 49.2.1
six        1.15.0
virtualenv 20.0.33
wheel      0.35.1
```

**Comment by Alejoss** [comment]
No es error del código del proyecto. psycopg2 requiere la instalación de otros paquetes, específicamente 

`sudo apt install libpq-dev python3-dev`

Es un error bastante conocido, si no les sirve este comando, puede googlear "psycopg2 install error" y van a encontrar bastante documentación al respecto.

**Comment by davElsanto** [comment]
El error se presenta al tratar de verificar la base de datos `postgresql`. Arreglado al installar `postgresql` usando homebrew `brew install postgresql` tambien verificar los paquetes de `openssl`, de no tenerlos instalarlo y actualizar el bash.

Posteriormente instalar los binarios de psyscopg2 `pip install psycopg2-binary==2.8.6`.

Para finalizar instalar las dependencias del proyecto `pip install -r requirements.txt`
