### ISSUE TITLE
Mostrar certificado

### ISSUE THREAD

**Issue by Alejoss** [Alejoss/academia_blockchain#17]
Crear un pdf mostrando el certificado que adquiere el usuario. El texto en el PDF debe poder editarse por el creador del evento. El creador del evento debe poder ver el pdf. Debe quedar bien, similar a un certificado educativo universitario. El usuario que recibe el certificado debe poder verlo dando click en "Ver Cerficiado" en la página de bookmarks en su perfil o en la lista de certificados en su perfil. Se debe crear el certificado dinámicamente con python y mostrarlo al usuario sin guardarlo en la base de datos.

**Comment by DizNicolasAmor** [comment]
Hola, acabo de submitear un PR para este issue, pero no me lo puedo asignar.

**Comment by Alejoss** [comment]
Se puede utilizar el punto de API `/courses/certificate_detail/<int:certificate_id>`
