### ISSUE TITLE
FRONT-0011: actualizar el certificado con transaction hash

### ISSUE THREAD

**Issue by DizNicolasAmor** [Alejoss/academia_blockchain#72]
La API de `certificate_detail` tendrá un campo para el hash de la transacción. Si el certificado no se encuentra aún en la blockchain, ese campo vendrá vacío. El frontend debe manejar estos dos casos:

- Si el certificado no tiene transaction hash, debe mostrarse el mensaje "Este certificado aún no se encuentra en la blockchain" o similar.
- SI el certificado sí tiene un transaction hash, debe mostrarlo.

**Comment by DizNicolasAmor** [comment]
Hola @Alejoss , favor de confirmar si los requerimientos están bien.
Puedes asignarme este issue y quedo a la espera de que la API esté lista para luego poder fixear la parte de frontend. Saludos.

**Comment by Alejoss** [comment]
Voy a cerrar este issue. Las comisiones en ETH son extremadamente altas y puede afectar a la usabilidad y a la imagen de la pagina. En el futuro esperamos enviar los certificados a alguna blockchain, la que tenga buenas devtools y transacciones baratas.
